### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by vijfhoek** [robin7331/malyan-m200-display-firmware#1]
Currently, the project does not have a license. It'd be great if you could add one, so contributors can know where their work goes (and so it's not technically illegal to fork/modify the code).

In case you're not familiar with licenses, I recommend the [MIT](https://tldrlegal.com/license/mit-license) (really permissive license) or the [Apache 2](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) license (which allows you to place warranty on the product and has some patent protection stuff).

Having the proper license also protects against angry people destroying their printers, quoting the MIT license:

>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**Comment by robin7331** [comment]
You are absolutely right!
Just added the MIT license.
